### ISSUE TITLE
Importing app content before INSTALLED_APPS

### ISSUE THREAD

**Issue by rbharadwaj9** [netdash/netdash#17]
While running `docker-compose up` the content inside each module in `apps_dev` is loaded first and then the name of the app is added to `INSTALLED_APPS` in `settings.py`
This way, when I run unit tests, the runner is unable to detect my app until I modified settings.py to include the app I am working on.

**Comment by jlost** [comment]
@rbharadwaj9 Is this still an issue, or was it resolved by #23?

**Comment by rbharadwaj9** [comment]
This issue just went away by itself. I didn't work on a fix but I think we can close the issue.
